// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAHEzEL0jobkwSWeR5I1nYmmBlb8i_DYKA',
    appId: '1:792823981127:web:213ebc2b530ec3cc58bd62',
    messagingSenderId: '792823981127',
    projectId: 'rafq-929c9',
    authDomain: 'rafq-929c9.firebaseapp.com',
    storageBucket: 'rafq-929c9.firebasestorage.app',
    measurementId: 'G-2LV6NBY27L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCe3CBTeOsX_BeiAm2IBOeQCZ9fytTFvnE',
    appId: '1:792823981127:android:16beee189430fa3e58bd62',
    messagingSenderId: '792823981127',
    projectId: 'rafq-929c9',
    storageBucket: 'rafq-929c9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCBiaLbpeyUHvTmq01E_7efLTSJcyUn2IM',
    appId: '1:792823981127:ios:2704d2f99280691658bd62',
    messagingSenderId: '792823981127',
    projectId: 'rafq-929c9',
    storageBucket: 'rafq-929c9.firebasestorage.app',
    iosBundleId: 'com.example.rafq1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCBiaLbpeyUHvTmq01E_7efLTSJcyUn2IM',
    appId: '1:792823981127:ios:2704d2f99280691658bd62',
    messagingSenderId: '792823981127',
    projectId: 'rafq-929c9',
    storageBucket: 'rafq-929c9.firebasestorage.app',
    iosBundleId: 'com.example.rafq1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAHEzEL0jobkwSWeR5I1nYmmBlb8i_DYKA',
    appId: '1:792823981127:web:554a9f40aaaed7ce58bd62',
    messagingSenderId: '792823981127',
    projectId: 'rafq-929c9',
    authDomain: 'rafq-929c9.firebaseapp.com',
    storageBucket: 'rafq-929c9.firebasestorage.app',
    measurementId: 'G-Z5NTE0M0WR',
  );
}
